### ISSUE TITLE
Typos in the docummentation

### ISSUE THREAD

**Issue by janekl** [transbioZI/RMTL#2]
Hey,

Nice work!

I noted that there are typos in the documentation for MTR_Grap function. 
* In the [code](https://github.com/transbioZI/RMTL/blob/20692185f9e3791773bc6c94822267eb23d9e2b5/R/MTR_Graph.R#L13) lam1 corresponds to the specialised regularization for the network constraint
* However, in the [documentation for this function](https://github.com/transbioZI/RMTL/blob/20692185f9e3791773bc6c94822267eb23d9e2b5/man/MTR_Graph.Rd#L45) this is confused with lam2.

It is a minor thing but I suggest that this convention be applied for other algorithms included.

You may also want to write this [Lam1](https://github.com/transbioZI/RMTL/blob/20692185f9e3791773bc6c94822267eb23d9e2b5/man/MTR_Graph.Rd#L25) in lower case.

**Comment by hank9cao** [comment]
Great thanks, the parameters are updated according to your finding,
